#!/usr/bin/env python

#input variables
varList = {}
#[<variable in trees>, <variable name for axes and titles>, <unit>]
varList['Brown'] = [#16 vars (merged 12 and 14 vars for low and high mass):
['AK4HTpMETpLepPt','S_{T}','GeV'],
['corr_met_singleLepCalc','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['NJets_singleLepCalc','AK4 jet multiplicity',''],
['mass_lepJets0','M(l,j_{1})','GeV'], 
['mass_lepJets1','M(l,j_{2})','GeV'],
['mass_lepJets2','M(l,j_{3})','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['minDR_lepJet','min[#DeltaR(l,j)]',''],
['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
['BJetLeadPt','p_{T}(b_{1})','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxBBpt','M(b,b) with max[p_{T}(b,b)]','GeV'],
['mass_maxBBmass','max[M(b,b)]','GeV'],
['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
['mass_lepJJ_minJJdr','M(l,jj) with min[#DeltaR(j,j)], j #neq b','GeV'],

# 'mass_minLLdr','theJetLeadPt','deltaR_lepJets0','deltaR_lepJets1','deltaR_lepJets2',
# 'minDR_lepBJet','minBBdr','mass_lepBJet0','mass_lepBB_minBBdr',
]

varList['POM'] = [#16 vars
['AK4HTpMETpLepPt','S_{T}','GeV'],
['AK4HT','H_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}(lep)','GeV'],
['corr_met_singleLepCalc','E_{T}^{miss}','GeV'],
['BJetLeadPt','p_{T}(b_{1})','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['mass_lepBJet_mindr','M(l,b) with min[#DeltaR(l,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['MT2bb','MT2bb','GeV'],
['MT2bbl','MT2bbl','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#Eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
]

varList['Comb'] = [#28 vars (merge POM and Brown vars):
['AK4HTpMETpLepPt','S_{T}','GeV'],
['corr_met_singleLepCalc','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['NJets_singleLepCalc','AK4 jet multiplicity',''],
['mass_lepJets0','M(l,j_{1})','GeV'], 
['mass_lepJets1','M(l,j_{2})','GeV'],
['mass_lepJets2','M(l,j_{3})','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['minDR_lepJet','min[#DeltaR(l,j)]',''],
['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
['BJetLeadPt','p_{T}(b_{1})','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxBBpt','M(b,b) with max[p_{T}(b,b)]','GeV'],
['mass_maxBBmass','max[M(b,b)]','GeV'],
['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
['mass_lepJJ_minJJdr','M(l,jj) with min[#DeltaR(j,j)], j #neq b','GeV'],
['AK4HT','H_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}(lep)','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['mass_lepBJet_mindr','M(l,b) with min[#DeltaR(l,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['MT2bb','MT2bb','GeV'],
['MT2bbl','MT2bbl','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#Eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
]

varList['BigComb'] = [#36 vars (merge Comb and Brown/25 vars):
['AK4HTpMETpLepPt','S_{T}','GeV'],
['corr_met_singleLepCalc','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
# ['NJets_singleLepCalc','AK4 jet multiplicity',''],
['mass_lepJets0','M(l,j_{1})','GeV'], 
['mass_lepJets1','M(l,j_{2})','GeV'],
['mass_lepJets2','M(l,j_{3})','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['minDR_lepJet','min[#DeltaR(l,j)]',''],
['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
['BJetLeadPt','p_{T}(b_{1})','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['mass_maxBBpt','M(b,b) with max[p_{T}(b,b)]','GeV'],
['mass_maxBBmass','max[M(b,b)]','GeV'],
['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['mass_lepJJ_minJJdr','M(l,jj) with min[#DeltaR(j,j)], j #neq b','GeV'],
['AK4HT','H_{T}','GeV'],
# ['leptonPt_singleLepCalc','p_{T}(lep)','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['mass_lepBJet_mindr','M(l,b) with min[#DeltaR(l,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['MT2bb','MT2bb','GeV'],
['MT2bbl','MT2bbl','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
['mass_minLLdr','M(j,j) with min[#DeltaR(j,j)], j #neq b','GeV'],
['theJetLeadPt','p_{T}(j_{1})','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['mass_lepBJet0','M(l,b_{1})','GeV'],
# ['mass_lepBB_minBBdr','M(l,bb) with min[#DeltaR(b,b)]','GeV'],
]

varList['APR9'] = [#33 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['mass_lepJets0','M(l,j_{1})','GeV'], 
['mass_lepJets1','M(l,j_{2})','GeV'],
['mass_lepJets2','M(l,j_{3})','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
['BJetLeadPt','p_{T}(b_{1})','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxBBmass','max[M(b,b)]','GeV'],
['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['mass_lepBJet_mindr','M(l,b) with min[#DeltaR(l,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['MT2bb','MT2bb','GeV'],
['MT2bbl','MT2bbl','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
['mass_minLLdr','M(j,j) with min[#DeltaR(j,j)], j #neq b','GeV'],
['theJetLeadPt','p_{T}(j_{1})','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['mass_lepBJet0','M(l,b_{1})','GeV'],
['aveCSVpt','p_{T} weighted CSVv2',''],
['PtFifthJet','5^{th} jet p_{T}','GeV'],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]

varList['MAY'] = [#21 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxBBmass','max[M(b,b)]','GeV'],
['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
['AK4HT','H_{T}','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','p_{T} weighted CSVv2',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]

varList['MAY24'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]

varList['MAY24NoLepJetBJetMETHTvsST'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoLepMETHTvsST'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoST'] = [#24 vars:
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoHT'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoLepPt'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoMET'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoLeadBJetPt'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoLeadJetPt'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['hemiout','Hemiout','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]
varList['MAY24NoHemiOut'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['AK4HT','H_{T}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['centrality','Centrality',''],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
]

inputDir = '/user_data/jlee/chargedHiggs/EPS2017/LJMet80X_1lep_051117_step2/nominal/'

bkg = [
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_10_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_11_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_12_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_13_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_1_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_2_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_3_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_4_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_5_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_6_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_7_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_8_hadd.root',
'TTToSemilepton_TuneCUETP8M2_ttHtranche3_13TeV-powheg-pythia8_9_hadd.root',

# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_10_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_11_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_1_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_2_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_3_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_4_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_5_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_6_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_7_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_8_hadd.root',
# 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8_9_hadd.root',
]

varList['Low'] = [#24 vars:
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['centrality','Centrality',''],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['AK4HT','H_{T}','GeV'],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['corr_met','E_{T}^{miss}','GeV'],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['AK4HTpMETpLepPt','S_{T}','GeV'],
['hemiout','Hemiout','GeV'],
]
varList['Med'] = [#24 vars:
['aveBBdr','ave[#DeltaR(b,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
['AK4HT','H_{T}','GeV'],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['centrality','Centrality',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['minMleppBjet','min[M(l,b)]','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['AK4HTpMETpLepPt','S_{T}','GeV'],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['hemiout','Hemiout','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
]
varList['0p8TeV'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['AK4HT','H_{T}','GeV'],
['centrality','Centrality',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['hemiout','Hemiout','GeV'],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['corr_met','E_{T}^{miss}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
]
varList['1TeV'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['AK4HT','H_{T}','GeV'],
['centrality','Centrality',''],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['FW_momentum_2','2^{nd} FW moment','GeV'],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['hemiout','Hemiout','GeV'],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['corr_met','E_{T}^{miss}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
]
varList['2TeV'] = [#24 vars:
['AK4HTpMETpLepPt','S_{T}','GeV'],
['centrality','Centrality',''],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['AK4HT','H_{T}','GeV'],
['FW_momentum_2','2^{nd} FW moment','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['hemiout','Hemiout','GeV'],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['corr_met','E_{T}^{miss}','GeV'],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
]
varList['3TeV'] = [#24 vars:
['centrality','Centrality',''],
['AK4HTpMETpLepPt','S_{T}','GeV'],
['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
['aveCSVpt','ave[CSVv2]^{p_{T} weighted}',''],
['FW_momentum_2','2^{nd} FW moment','GeV'],
['aveBBdr','ave[#DeltaR(b,b)]',''],
['minDR_lepBJet','min[#DeltaR(l,b)]',''],
['deltaR_minBB','min[#DeltaR(b,b)]',''],
['AK4HT','H_{T}','GeV'],
['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
['deltaR_lepBJet_maxpt','#DeltaR(l,b)]^{max[p_{T}(l,b)]}',''],
['hemiout','Hemiout','GeV'],
['theJetLeadPt','p_{T}^{j_{1}}','GeV'],
['mass_maxJJJpt','M(jjj)^{max[p_{T}(jjj)]}','GeV'],
['lepDR_minBBdr','#DeltaR(l,bb)^{min[#DeltaR(b,b)]}',''],
['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
['corr_met','E_{T}^{miss}','GeV'],
['minMleppBjet','min[M(l,b)]','GeV'],
['leptonPt_singleLepCalc','p_{T}^{lep}','GeV'],
['BJetLeadPt','p_{T}^{b_{1}}','GeV'],
['mass_minBBdr','M(b,b) with min[#DeltaR(b,b)]','GeV'],
]
for ind in range(1,25):
	varList['Low'+str(ind)]=varList['Low'][:ind]
	varList['Med'+str(ind)]=varList['Med'][:ind]
	varList['0p8TeV'+str(ind)]=varList['0p8TeV'][:ind]
	varList['1TeV'+str(ind)]=varList['1TeV'][:ind]
	varList['2TeV'+str(ind)]=varList['2TeV'][:ind]
	varList['3TeV'+str(ind)]=varList['3TeV'][:ind]

# varList['Low'] = [#21 vars:
# ['deltaR_minBB','min[#DeltaR(b,b)]',''],
# ['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
# ['FW_momentum_2','2^{nd} FW moment','GeV'],
# ['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['aveCSVpt','p_{T} weighted CSVv2',''],
# ['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
# ['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
# ['centrality','Centrality',''],
# ['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
# ['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
# ['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
# ['corr_met','E_{T}^{miss}','GeV'],
# ['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['minDR_lepBJet','min[#DeltaR(l,b)]',''],
# ['minMleppBjet','min[M(l,b)]','GeV'],
# ['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
# ['AK4HT','H_{T}','GeV'],
# ['mass_maxBBmass','max[M(b,b)]','GeV'],
# ['hemiout','Hemiout','GeV'],
# ['AK4HTpMETpLepPt','S_{T}','GeV'],
# ]
# 
# varList['Med'] = [#21 vars:
# ['deltaR_minBB','min[#DeltaR(b,b)]',''],
# ['FW_momentum_2','2^{nd} FW moment','GeV'],
# ['AK4HT','H_{T}','GeV'],
# ['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['aveCSVpt','p_{T} weighted CSVv2',''],
# ['centrality','Centrality',''],
# ['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
# ['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
# ['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
# ['mass_maxBBmass','max[M(b,b)]','GeV'],
# ['minMleppBjet','min[M(l,b)]','GeV'],
# ['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
# ['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
# ['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
# ['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
# ['AK4HTpMETpLepPt','S_{T}','GeV'],
# ['minDR_lepBJet','min[#DeltaR(l,b)]',''],
# ['corr_met','E_{T}^{miss}','GeV'],
# ['hemiout','Hemiout','GeV'],
# ]
# 
# varList['0p8TeV'] = [#21 vars:
# ['AK4HTpMETpLepPt','S_{T}','GeV'],
# ['AK4HT','H_{T}','GeV'],
# ['centrality','Centrality',''],
# ['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
# ['FW_momentum_2','2^{nd} FW moment','GeV'],
# ['aveCSVpt','p_{T} weighted CSVv2',''],
# ['deltaR_minBB','min[#DeltaR(b,b)]',''],
# ['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
# ['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['hemiout','Hemiout','GeV'],
# ['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
# ['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['mass_maxBBmass','max[M(b,b)]','GeV'],
# ['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
# ['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
# ['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
# ['minDR_lepBJet','min[#DeltaR(l,b)]',''],
# ['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
# ['corr_met','E_{T}^{miss}','GeV'],
# ['minMleppBjet','min[M(l,b)]','GeV'],
# ]
# 
# varList['1TeV'] = [#21 vars:
# ['AK4HTpMETpLepPt','S_{T}','GeV'],
# ['AK4HT','H_{T}','GeV'],
# ['centrality','Centrality',''],
# ['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
# ['FW_momentum_2','2^{nd} FW moment','GeV'],
# ['aveCSVpt','p_{T} weighted CSVv2',''],
# ['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
# ['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
# ['deltaR_minBB','min[#DeltaR(b,b)]',''],
# ['hemiout','Hemiout','GeV'],
# ['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
# ['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
# ['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['mass_maxBBmass','max[M(b,b)]','GeV'],
# ['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['minDR_lepBJet','min[#DeltaR(l,b)]',''],
# ['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
# ['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
# ['corr_met','E_{T}^{miss}','GeV'],
# ['minMleppBjet','min[M(l,b)]','GeV'],
# ]
# 
# varList['2TeV'] = [#21 vars:
# ['AK4HTpMETpLepPt','S_{T}','GeV'],
# ['centrality','Centrality',''],
# ['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
# ['FW_momentum_2','2^{nd} FW moment','GeV'],
# ['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
# ['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
# ['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
# ['AK4HT','H_{T}','GeV'],
# ['aveCSVpt','p_{T} weighted CSVv2',''],
# ['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
# ['minDR_lepBJet','min[#DeltaR(l,b)]',''],
# ['deltaR_minBB','min[#DeltaR(b,b)]',''],
# ['hemiout','Hemiout','GeV'],
# ['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
# ['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
# ['mass_maxBBmass','max[M(b,b)]','GeV'],
# ['corr_met','E_{T}^{miss}','GeV'],
# ['minMleppBjet','min[M(l,b)]','GeV'],
# ]
# 
# varList['3TeV'] = [#21 vars:
# ['AK4HTpMETpLepPt','S_{T}','GeV'],
# ['centrality','Centrality',''],
# ['deltaR_lepJets0','#DeltaR(l,j_{1})',''],
# ['aveCSVpt','p_{T} weighted CSVv2',''],
# ['deltaR_lepJets2','#DeltaR(l,j_{3})',''],
# ['deltaR_lepJets1','#DeltaR(l,j_{2})',''],
# ['deltaEta_maxBB','max[#Delta#eta(b,b)]',''],
# ['FW_momentum_2','2^{nd} FW moment','GeV'],
# ['lepDR_minBBdr','#DeltaR(l,bb) with min[#DeltaR(b,b)]',''],
# ['AK4HT','H_{T}','GeV'],
# ['deltaR_minBB','min[#DeltaR(b,b)]',''],
# ['minDR_lepBJet','min[#DeltaR(l,b)]',''],
# ['aveBBdr','ave[#DeltaR(b,b)]',''],
# ['deltaR_lepBJets0','#DeltaR(l,b_{1})',''],
# ['mass_maxJJJpt','M(jjj) with max[p_{T}(jjj)]','GeV'],
# ['deltaR_lepBJet_maxpt','#DeltaR(l,b)] with max[p_{T}(l,b)]',''],
# ['hemiout','Hemiout','GeV'],
# ['MT_lepMet','M_{T}(lep,E_{T}^{miss})','GeV'],
# ['corr_met','E_{T}^{miss}','GeV'],
# ['mass_maxBBmass','max[M(b,b)]','GeV'],
# ['minMleppBjet','min[M(l,b)]','GeV'],
# ]

